### ISSUE TITLE
Unable to add tools

### ISSUE THREAD

**Issue by tichita7** [akshatmittal61/new-tab-extension#1]
On adding a new todo, the item disappears and unable to view even after refresh.
Steps to reproduce:
1. Install the extension on your chrome browser
2. In the right todo panel, enter the text for a new item.
3. Add the item by submitting the form.

Expected behavior:
Todo should be added, and displayed on the list

**Comment by akshatmittal61** [comment]
This issue has been fixed in #2 . Please check now.
